name: fetch origin
on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/rating-chart.yml
      - .github/workflows/build-binaries.yml
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }} # 令牌
           upstream_repository: 1715173329/UnblockNeteaseMusic  # 上游仓库
           target_repository: gchengyu/UnblockNeteaseMusic  # 你要推送的仓库
           upstream_branch: enhanced  # 默认是拉取上游仓库的 master 分支
           target_branch: enhanced # 默认推送到你的仓库 master 分支
           force: false  # 是否强制推送
           tags: true  # 确定是否使用 - tags
